---
driver:
  name: vagrant
  boot_timeout: 1440

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  connection_timeout: 1440

platforms:
  - name: windows2016
    driver:
      box: windows2016
      vm_hostname: windows2016

suites:
  - name: default
    run_list:
      - recipe[test_cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
